### ISSUE TITLE
Document custom layouts

### ISSUE THREAD

**Issue by vi** [hq6/smux#1]
In smux's documentation it is written, that

> LAYOUT,
>        One of the five standard tmux layouts, given below.
>        even-horizontal, even-vertical, main-horizontal, main-vertical, tiled.

, but in reality Tmux also supports custom layouts (for fixed maximum number of windows), like `LAYOUT=88b5,174x48,0,0{87x48,0,0[87x6,0,0,209,87x5,0,7,217,87x5,0,13,213,87x5,0,19,218,87x5,0,25,211,87x5,0,31,219,87x5,0,37,215,87x5,0,43,220],86x48,88,0[86x6,88,0,210,86x5,88,7,221,86x5,88,13,214,86x5,88,19,222,86x5,88,25,212,86x5,88,31,223,86x5,88,37,216,86x5,88,43,224]}` to have two columns of a lot of narrow panes.

smux's documentation can link to tmux's documentation:

>In addition, select-layout may be used to apply a previously used
>layout - the list-windows command displays the layout of each
>window in a form suitable for use with select-layout.  For example:
>
>   
>           $ tmux list-windows
>           0: ksh [159x48]
>               layout: bb62,159x48,0,0{79x48,0,0,79x48,80,0}
>           $ tmux select-layout bb62,159x48,0,0{79x48,0,0,79x48,80,0} 
>

**Comment by hq6** [comment]
Thank you for raising this, and sorry I haven't been watching this repo.

I still use smux.py myself but haven't had to change its behavior in a couple of years.
