### ISSUE TITLE
smux corrupted

### ISSUE THREAD

**Issue by jsha129** [hq6/smux#2]
Hi there,
Thanks for developing smux. It's very handy on HPC. 
I think i pressed some keys in a smux session and it seems to be broken now. Are there any config files smux reads prior to loading? thanks

**Comment by hq6** [comment]
Sorry I haven't been watching this repo. No, smux doesn't read any config files beyond what you pass it.
However, it uses the tmux cli and that reads the normal `~/.tmux.conf`.

**Comment by hq6** [comment]
Closing this issue since there hasn't been further activity on it.

Please reopen if you have repro steps.
